
-- THE IMPLEMENTATION OF ENUMS ON THE DATABASE... O_o

CREATE TABLE TransportStatuses
(
	Id INT NOT NULL,
	-- DUE TO ENUM-INDEX CAN DUPLICATE BUT NOT STRING-VALUE.
	Status NVARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE InspectionStatuses
(
	Id INT NOT NULL,
	Status NVARCHAR(50) NOT NULL PRIMARY KEY
);

-- END OF ENUMS

-- TABLES OF THE MAIN ENTITIES

CREATE TABLE Users
(
	-- ABSTRACT USER
	IdNumber NVARCHAR(100) NOT NULL PRIMARY KEY,
	FirstName NVARCHAR(150) NOT NULL,
	LastName NVARCHAR(150) NOT NULL,
	DateOfBirth Date NOT NULL,
	Password NVARCHAR(250) NOT NULL,
	UserName NVARCHAR(150) NOT NULL,
	-- CUSTOMER
	BasicDiscount FLOAT NULL,
	PassportNumber NVARCHAR(100) NULL,
	DrivingLicenseNumber NVARCHAR(100) NULL,
	-- INSPECTOR
	EmployementDate DATETIME NULL

	-- CONNECTIONS TO: [Cars] (1 — MANY), [Deals] (1 — MANY), [Inspections] (1 — MANY).
);

CREATE TABLE Deals
(
	Name NVARCHAR(250) NOT NULL,
	CustomerId NVARCHAR(100) NOT NULL, -- IT IS NOT IdNumber FROM User, IT IS PassportNumber... O_o
	-- SO NO COMPROMISE OF FIRST NROMAL-FORM, Я ДУМЯЮ... о_О
	CONSTRAINT PK_Deals_Name_CustomerId
		PRIMARY KEY (Name, CustomerId),
	IdNumber NVARCHAR(100) NOT NULL,
	FOREIGN KEY (IdNumber)
		REFERENCES Users (IdNumber),
	CarId NVARCHAR(100) NOT NULL,
	Price FLOAT NOT NULL

	-- ENTITY CONNECTIONS: [Users] (MANY - 1), [Cars] (MANY - 1), THROUGH PROPERTIES.
);

CREATE TABLE Mechanicists
(
	Id NVARCHAR(100) NOT NULL PRIMARY KEY,
	Year INT NOT NULL,
	Name NVARCHAR(150) NOT NULL,
	Surename NVARCHAR(150) NOT NULL

	-- ENTITY CONNECTED TO [Repairs] (1 - MANY), DIRECTLY.
);

CREATE TABLE Cars
(
	CarId NVARCHAR(100) NOT NULL,
	VinCode NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_CarId_VinCode
		PRIMARY KEY (CarId, VinCode),
	Status NVARCHAR(50) NULL,
	-- AN ATTEMPT TO IMPLEMENT ENUMS.
	-- CHECK(Status IN ('Unknown', 'Available', 'Rented', 'Sold', 'InRepair', 'Unavailable'))
	-- DEFAULT 'Unknown'
	FOREIGN KEY (Status)
		REFERENCES TransportStatuses (Status),
	-- DEAL CONNECTION (Car HAS ONE DEAL)
	Name NVARCHAR(250) NOT NULL,
	-- CONNECTION TO Customer, (MANY - 1)
	CustomerId NVARCHAR(100) UNIQUE NOT NULL,
	FOREIGN KEY (Name, CustomerId)
		REFERENCES Deals (Name, CustomerId),
	NumberPlate NVARCHAR(50) NOT NULL,
	Brand NVARCHAR(500) NOT NULL,
	Model NVARCHAR(500) NOT NULL,
	Price INT NOT NULL,
	NumberOfSeats INT NULL,
	NumberOfDoors INT NULL,
	Mileage FLOAT NULL,
	MaxFuelCapacity INT NULL,
	CurrentFuel FLOAT NULL,
	Year DATE NULL,
	IsFitForUse BIT NULL

	-- ENTITY CONNECTIONS: [Deals] (1 — 1) V, [Inspections] (1 — MANY) V,
	-- [Customer] (MANY - 1) V, [Repairs] (1 - MANY).
	-- DIRECTLY BY TYPES AND COLLECTIONS OF TYPE.
);

CREATE TABLE Inspections
(
	InspectionId NVARCHAR(100) NOT NULL PRIMARY KEY,
	-- INSPECTION CONNECTION TO Car, (MANY - 1).
	CarId NVARCHAR(100) NOT NULL,
	VinCode NVARCHAR(100) NOT NULL,
	FOREIGN KEY (CarId, VinCode)
		REFERENCES Cars (CarId, VinCode),
	-- INSPECTION CONNECTION TO STATUS ENUM.
	FOREIGN KEY (Result)
		REFERENCES InspectionStatuses (Status),
	IdNumber NVARCHAR(100) NOT NULL,
	FOREIGN KEY (IdNumber)
		REFERENCES Users (IdNumber),
	InspectionDate DATE NULL,
	--InspectorName NVARCHAR(250) NULL, TRANSITIVE DEPENDANCY???
	Result NVARCHAR(50) NULL

	-- ENTITY CONNECTIONS: [Cars] (MANY - 1) V, [Inspectors] (MANY — 1) V THROUGH PROPERTIES.
);

CREATE TABLE Repairs
(
	Id NVARCHAR(500) NOT NULL PRIMARY KEY,
	Date DATETIME NOT NULL,
	-- CONNECTION TO CARS (REPAIR HAS ONE CAR, CAR HAS MANY REPAIRS)
	CarId NVARCHAR(100) NOT NULL,
	VinCode NVARCHAR(100) NOT NULL,
	FOREIGN KEY (CarId, VinCode)
		REFERENCES Cars (CarId, VinCode),
	MechanicName NVARCHAR(250) NULL,
	MechanicId NVARCHAR(100) NOT NULL,
	-- CONNECTION TO MECHANICISTS (ONE MECHANIC HAS MANY REPAIRS)
	FOREIGN KEY (MechanicId)
		REFERENCES Mechanicists (Id),
	CarBrand NVARCHAR(500) NULL,
	CarModel NVARCHAR(500) NULL,
	-- TECHNICAL INFORMATION CAN CONSIST OF MUCH OF DATA.
	TechnicalInfo TEXT NULL,
	IsSuccessfull BIT NOT NULL,
	TotalCost INT NOT NULL

	-- CONNECTED TO: [Mechanics] (MANY - 1) V, [Cars] (MANY - 1) V DIRECTLY.
);



-- END OF MAIN ENTITIES

-- ALTERATION SECTION

--ALTER TABLE Inspections
--ADD CONSTRAINT FK_Cars_CarId_VinCode_Inspections
--	FOREIGN KEY (CarId, VinCode)
--		REFERENCES Cars (CarId, VinCode);

-- END OF ALTERATIONS

-- INSERT VALUE SECTION

INSERT INTO TransportStatuses
	VALUES
	   (0, 'Unknown'),
	   (1, 'Available'),
	   (2, 'Rented'),
	   (3, 'Sold'),
	   (4, 'InRepair'),
	   (200, 'Unavailable');

INSERT INTO InspectionStatuses
	VALUES
	   (0, 'Unknown'),
       (1, 'Successfully'),
       (2, 'Repair'),
       (3, 'Unusable');

-- SOME DATA TAKEN FROM MR. D. IBRAHIMOV'S BRANCH, AND O. KARMANSKYI CODE.
-- SOME TUPLE MUST BE NULL TO REPRESENT CUSTOMER, INSPECTOR.
INSERT INTO Users
	VALUES
		(
			'615A5A48-5C4B-49F9-900B-0241134D640C',
			'Olga',
			'Ivanenko',
			'1987-12-03T00:00:00',
			'1234BB385678C6533DC7CF4A',
			'Olga',
			0.5,
			'RW293589',
			'895609'
		),
		(
			'67F84A48-B96B-4A16-BB38-6C641F8504CC',
			'Alex',
			'Petrov',
			'1984-11-03T00:00:00',
			'87654BB38321C6533DCBB387CF4A',
			'Alex',
			0.2,
			'VW634101',
			'626825'
		),
		(
			'3B8BE39A-0738-4B15-93C9-3AA1620CBC5A',
			'Maria',
			'Sidorova',
			'1981-12-05T00:00:00',
			'123BB38487BB3865C6533DC7CF4A',
			'Maria',
			0.2,
			'MG225941',
			'172860'
		),
		(
			'BEC62BF5-35AB-45B0-A3AA-BA6A5F3EEBB2',
			'Igor',
			'Kuznetsov',
			'1999-11-03T00:00:00',
			'567BB388123BB384C6533DC7CF4A',
			'Igor',
			0.5,
			'SL882705',
			'242445'
		),
		(
			'BF016BBD-0AF3-412A-B8CD-C6533DC7CF4A',
			'Elena',
			'Nikolaeva',
			'1987-10-03T00:00:00',
			'C653BB383DCBB387CF4A',
			'Elena',
			0.5,
			'UX764750',
			'488237'
		);

INSERT INTO DEALS
-- END OF INSER VALUES SECTION